__dependents_rules__(
    ("*", "*"),
)

__dependencies_rules__(
    ("*", "//shared/foundation/src/**", "!*"),
)

python_sources(
    name="lib",
    sources=["**/*.py"],
    tags=["shared:foundation"],
)
