__dependents_rules__(
    ("*", {"tags": ["svc:pantsagon"]}, "!*"),
)

__dependencies_rules__(
    ("*", "//services/pantsagon/src/pantsagon", "!*"),
)

python_sources(
    name="pkg",
    sources=["__init__.py"],
    tags=["svc:pantsagon"],
)
