__dependents_rules__ = [{"tags": ["svc:pantsagon"]}]

python_sources(
  name="domain",
  tags=["svc:pantsagon", "layer:domain"],
  dependencies=["//shared/foundation:lib"],
  __dependencies_rules__=[
    {"path": "services/pantsagon/src/pantsagon/domain/**"},
    {"path": "shared/foundation/src/**"},
  ],
)
